version: '2.2'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /opt/app
    volumes:
      - ./frontend:/opt/app
    ports:
      - 4200:4200
    command: bash -c 'yarn install && ng serve --host 0.0.0.0'
    stdin_open: true
    tty: true
  websocket:
    image: node:latest
    environment:
      HOST_UID: 1000
      NODE_ENV: development
    ports:
      - '8081:8081'
    volumes:
      - './websocket-server:/opt/app'
    cpu_quota: 75000
    links:
      - 'frontend:frontend'
    working_dir: /opt/app
    command: bash -c "npm install && npm run start"
